#!/usr/bin/env ruby

#
# This file is part of the `src-run/latex-style-builder` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, please view the LICENSE.md
# file that was distributed with this source code.
#

require 'commander'
require 'open_uri_redirections'
require 'nokogiri'
require 'handlebars'
require_relative 'lib/Application'

Application.new.run if $0 == __FILE__

# EOF
